name: default-environment-variables

on: [push]

jobs:
    sample-job:
        name: Synapse CD
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        environment: ${GITHUB_REF##*/}
        
        steps:
        
            - name: Checkout local
              uses: actions/checkout@v2
              
            - name: Stop Synapse Triggers
              run: |
                az synapse trigger stop --name "TriggerName" --workspace-name "${{ secrets.WORKSPACE }}"
            - name: Synapse workspace deployment
              uses: Azure/Synapse-workspace-deployment@V1.7.0
              with:
                  TargetWorkspaceName: '${{ secrets.WORKSPACE }}'
                  TemplateFile: './TemplateForWorkspace.json'
                  DeleteArtifactsNotInTemplate: true
                  ParametersFile: './TemplateParametersForWorkspace.json'
                  environment: 'Azure Public'
                  resourceGroup: '${{ secrets.RESOURCE_GROUP}}'
                  clientId: ${{ secrets.CLIENT_ID }}
                  clientSecret: ${{ secrets.CLIENT_SECRET }}
                  subscriptionId: ${{ secrets.SUB_ID }}
                  tenantId: ${{ secrets.TENANT_ID }}
                  operation: 'deploy'
                  
            - name: Start Synapse Triggers
              run: |
                az synapse trigger start --name "TriggerName" --workspace-name "${{ secrets.WORKSPACE }}"
                
                
                
