name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  name: Synapse CD
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    environment: ${GITHUB_REF##*/}

    steps:

      - name: Checkout local
        uses: actions/checkout@v2

      - name: Stop Synapse Triggers
        run: |
          az synapse trigger stop --name "TriggerName" --workspace-name "${{ secrets.WORKSPACE }}"

      - uses: Azure/synapse-workspace-deployment@v1.6.0
        with:
          TargetWorkspaceName: '${{ secrets.WORKSPACE }}'
          TemplateFile: './TemplateForWorkspace.json'
          DeleteArtifactsNotInTemplate: true
          ParametersFile: './TemplateParametersForWorkspace.json'
          environment: 'Azure Public'
          resourceGroup: '${{ secrets.RESOURCE_GROUP}}'
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          subscriptionId: ${{ secrets.SUB_ID }}
          tenantId: ${{ secrets.TENANT_ID }}
          operation: 'deploy'

      - name: Start Synapse Triggers
        run: |
          az synapse trigger start --name "TriggerName" --workspace-name "${{ secrets.WORKSPACE }}"
